services:
  db:
    build:
      context: ./db_dockerfile
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  backend:
    build:
      context: ./app
    container_name: my_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  frontend:
    build:
      context: ./frontend
    container_name: my_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules

volumes:
  node_modules:
  postgres_data:
